// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum EnumClass: String, CaseIterable, Codable {
  case abc = "_abc"
  case minusEfg = "-efg"
  case xyz = "(xyz)"
}
