// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public enum BundleIDPlatform: String, CaseIterable, Codable {
	case iOS = "IOS"
	case macOS = "MAC_OS"
}
