// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation

public struct C: Codable {
    public var kind: String

    public init(kind: String) {
        self.kind = kind
    }

    public init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.kind = try values.decode(String.self, forKey: "kind")
    }

    public func encode(to encoder: any Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(kind, forKey: "kind")
    }
}
