// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

struct ArrayOfNumberOnly: Codable {
    var arrayNumber: [Double]?

    init(arrayNumber: [Double]? = nil) {
        self.arrayNumber = arrayNumber
    }

    init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.arrayNumber = try values.decodeIfPresent([Double].self, forKey: "ArrayNumber")
    }

    func encode(to encoder: any Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(arrayNumber, forKey: "ArrayNumber")
    }
}
