// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

struct ReadOnlyFirst: Codable {
    var bar: String?
    var baz: String?

    init(bar: String? = nil, baz: String? = nil) {
        self.bar = bar
        self.baz = baz
    }

    init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.bar = try values.decodeIfPresent(String.self, forKey: "bar")
        self.baz = try values.decodeIfPresent(String.self, forKey: "baz")
    }

    func encode(to encoder: any Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encodeIfPresent(bar, forKey: "bar")
        try values.encodeIfPresent(baz, forKey: "baz")
    }
}
