// Generated by Create API
// https://github.com/CreateAPI/CreateAPI

import Foundation
import NaiveDate

public struct Image: Codable {
    public var identifier: String
    public var url: String

    public init(identifier: String, url: String) {
        self.identifier = identifier
        self.url = url
    }

    public init(from decoder: any Decoder) throws {
        let values = try decoder.container(keyedBy: StringCodingKey.self)
        self.identifier = try values.decode(String.self, forKey: "id")
        self.url = try values.decode(String.self, forKey: "url")
    }

    public func encode(to encoder: any Encoder) throws {
        var values = encoder.container(keyedBy: StringCodingKey.self)
        try values.encode(identifier, forKey: "id")
        try values.encode(url, forKey: "url")
    }
}
